Add support for SG, Volume Types, AZ and fix for disk indexing
vexxhost/migratekit pull request #5
Opened 2024-07-11 14:50 UTC by dswebbthg

4 Optional Flags added
- Added security group support during port creation
- Volume type for block devices (if not supplied will default to OS default volume type)
- Availibility zones for the virtual machine and block device (single mapping for both).
- The ability to disable running virt-v2v-inplace (defaults to running it)

1 Bug fix:

- Added disk index for multi disk migrations as without it the server creation would fail.

2024-07-12 15:51 UTC, mnaser requested changes
Awesome.  There are a few things that would make things neater.  If you want me to pick this up, I'll be glad to.

2024-07-15 12:49 UTC, cohl790 commented
> 4 Optional Flags added
> 
> * Added security group support during port creation
> * Volume type for block devices (if not supplied will default to OS default volume type)
> * Availibility zones for the virtual machine and block device (single mapping for both).
> * The ability to disable running virt-v2v-inplace (defaults to running it)
> * The ability to define virtio-scsi and virtio for disk device types
> 
> 1 Change:
> 
> * Moved volume metadata updates to map prior to volume creation.
> 
> 1 Bug fix:
> 
> * Added disk index for multi disk migrations as without it the server creation would fail.

Having the option for volume type would be a great enhancement.

2024-07-15 13:10 UTC, dswebbthg commented on main.go
> +	cutoverCmd.Flags().StringVar(&securityGroups, "security-groups", "", "Openstack security groups, comma separated (e.g. '42c5a89e-4034-4f2a-adea-b33adc9614f4,6647122c-2d46-42f1-bb26-f38007730fdc')")
Nice, I didn't see that was an option.

2024-07-18 14:21 UTC, dswebbthg commented on internal/target/openstack.go
> +	}
I'm not sure tbh.  I'm assuming you could query VMWare to look at it's disk controllers but I'm not sure how that would be done.

2024-07-18 14:21 UTC, dswebbthg commented on main.go
> +	rootCmd.PersistentFlags().StringVar(&busType, "disk-bus-type", "virtio", "Specifies the type of disk controller to attach disk devices to.")
done

2024-07-22 13:16 UTC, michael-salo commented on internal/target/openstack.go
> +	}
yeah, it's not something that can be automatically detect from the source VM.

2024-07-22 13:27 UTC, mnaser approved these changes

2024-07-22 13:27 UTC, mnaser commented on internal/target/openstack.go
> +	}
Ok, got it, will mark as resolved then.

2024-07-22 13:27 UTC, mnaser commented
@dswebbthg This looks good to me at this points, am I good to proceed with merging or you have a few more things to add?

2024-07-22 13:33 UTC, michael-salo approved these changes
LGTM

2024-07-25 19:13 UTC, merged